name: Publish
on:
  workflow_call:

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: "ghcr.io/audiowalk-cz/portal:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
