name: Release to DEV

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Set short SHA
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs:
      - version
    uses: ./.github/workflows/_build.yaml
    with:
      image: ghcr.io/audiowalk-cz/portal:dev
      target: portal
      version: DEV-${{ needs.version.outputs.version }}

  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    with:
      images: ghcr.io/audiowalk-cz/portal:dev
    secrets: inherit

  tag:
    name: Tag
    needs:
      - build
    uses: ./.github/workflows/_tag.yaml
    with:
      tag: DEV
